version: '3.8'

services:
  backend:
    image: aimen123/backend:latest
    container_name: backend-jenkins
    ports:
      - "5001:5000"      # Changed to avoid conflict with Part-I
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    image: aimen123/frontend:latest
    container_name: frontend-jenkins
    ports:
      - "8082:80"         # Changed port to avoid conflict
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

  mongo:
    image: mongo:6
    container_name: mongo-jenkins
    restart: unless-stopped
    ports:
      - "27018:27017"    # Changed host port to avoid conflict
    volumes:
      - mongo_data_jenkins:/data/db
    networks:
      - app-network

volumes:
  mongo_data_jenkins:

networks:
  app-network:
    driver: bridge
