# # version: '3.8'

# # services:
# #   backend:
# #     build:
# #       context: ./backend
# #     container_name: backend
# #     ports:
# #       - "5000:5000"
# #     env_file:
# #       - ./backend/.env
# #     restart: unless-stopped
# #     networks:
# #       - app-network

# #   frontend:
# #     build:
# #       context: ./frontend
# #     container_name: frontend
# #     ports:
# #       - "8080:80"
# #     depends_on:
# #       - backend
# #     restart: unless-stopped
# #     networks:
# #       - app-network

# # networks:
# #   app-network:
# #     driver: bridge



# version: '3.8'

# services:
#   backend:
#     image: aimen123/backend
#     container_name: backend
#     ports:
#       - "5000:5000"
#     env_file:
#       - ./backend/.env
#     depends_on:
#       - mongo
#     restart: unless-stopped
#     networks:
#       - app-network

#   frontend:
#     image: aimen123/frontend
#     container_name: frontend
#     ports:
#       - "8080:80"
#     depends_on:
#       - backend
#     restart: unless-stopped
#     networks:
#       - app-network

#   mongo:
#     image: mongo:6
#     container_name: mongo
#     restart: unless-stopped
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo_data:/data/db
#     networks:
#       - app-network

# volumes:
#   mongo_data:

# networks:
#   app-network:
#     driver: bridge

version: '3.8'

services:
  backend-jenkins:
    image: aimen123/backend:latest
    container_name: backend-jenkins
    ports:
      - "5001:5000"           # Avoid conflict with Part-I backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app         # Mount code for Jenkins pipeline
    depends_on:
      - mongo-jenkins
    restart: unless-stopped
    networks:
      - app-network

  frontend-jenkins:
    image: aimen123/frontend:latest
    container_name: frontend-jenkins
    ports:
      - "8082:80"              # Avoid conflict with Part-I frontend
    volumes:
      - ./frontend:/app         # Mount code for Jenkins pipeline
    depends_on:
      - backend-jenkins
    restart: unless-stopped
    networks:
      - app-network

  mongo-jenkins:
    image: mongo:6
    container_name: mongo-jenkins
    ports:
      - "27018:27017"          # Avoid conflict with Part-I mongo
    volumes:
      - mongo_data_jenkins:/data/db
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mongo_data_jenkins:

networks:
  app-network:
    driver: bridge
