version: '3.8'

services:
  backend:
    build: ./backend      # Instead of pulling prebuilt image, Jenkins will build from code
    container_name: backend-jenkins
    ports:
      - "5001:5000"      # Changed to avoid conflict with Part-I
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - ./backend:/app/backend  # Volume for live code updates

  frontend:
    build: ./frontend
    container_name: frontend-jenkins
    ports:
      - "8082:80"         # Changed port to avoid conflict
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - ./frontend:/app/frontend

  mongo:
    image: mongo:6
    container_name: mongo-jenkins
    restart: unless-stopped
    ports:
      - "27018:27017"    # Changed host port to avoid conflict
    volumes:
      - mongo_data_jenkins:/data/db
    networks:
      - app-network

volumes:
  mongo_data_jenkins:

networks:
  app-network:
    driver: bridge
